-- Deck SRS ayarlari
ALTER TABLE "Deck" ADD COLUMN "learningSteps" TEXT NOT NULL DEFAULT '1,10';
ALTER TABLE "Deck" ADD COLUMN "graduatingInterval" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Deck" ADD COLUMN "easyInterval" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "Deck" ADD COLUMN "relearningSteps" TEXT NOT NULL DEFAULT '10';
ALTER TABLE "Deck" ADD COLUMN "lapseMinInterval" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Deck" ADD COLUMN "leechThreshold" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Deck" ADD COLUMN "maxInterval" INTEGER NOT NULL DEFAULT 36500;
ALTER TABLE "Deck" ADD COLUMN "startingEase" INTEGER NOT NULL DEFAULT 250;
ALTER TABLE "Deck" ADD COLUMN "easyBonus" INTEGER NOT NULL DEFAULT 130;
ALTER TABLE "Deck" ADD COLUMN "intervalModifier" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Deck" ADD COLUMN "hardModifier" INTEGER NOT NULL DEFAULT 120;

-- Card cok adimli ogrenme indeksi
ALTER TABLE "Card" ADD COLUMN "learningStep" INTEGER NOT NULL DEFAULT 0;
